Traceback (most recent call last):
  File "C:\Users\tirab\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\tirab\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\tirab\AppData\Roaming\Python\Python310\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\tirab\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\tirab\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\tirab\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\tirab\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Orden incorrecto 1
repetir_instrucciones_1()

def imprimir_instrucciones_1():
    print ("Abra el  recipiente.")
    print ("Complete el recipiente con agua.")

def repetir_instrucciones_1():
    imprimir_instrucciones_1()
    imprimir_instrucciones_1()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[19], line 2[0m
[0;32m      1[0m [38;5;66;03m# Orden incorrecto 1[39;00m
[1;32m----> 2[0m [43mrepetir_instrucciones_1[49m()
[0;32m      4[0m [38;5;28;01mdef[39;00m [38;5;21mimprimir_instrucciones_1[39m():
[0;32m      5[0m     [38;5;28mprint[39m ([38;5;124m"[39m[38;5;124mAbra el  recipiente.[39m[38;5;124m"[39m)

[1;31mNameError[0m: name 'repetir_instrucciones_1' is not defined

